import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { LocationData } from '@/types';

export const exportToPDF = (locations: LocationData[]): void => {
  const doc = new jsPDF();
  
  // Cover page
  doc.setFontSize(24);
  doc.text('UnQTraker Report', 105, 40, { align: 'center' });
  
  doc.setFontSize(12);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 105, 60, { align: 'center' });
  doc.text(`Total Locations: ${locations.length}`, 105, 70, { align: 'center' });
  
  // Statistics
  const uniqueSessions = new Set(locations.map(loc => loc.sessionId)).size;
  doc.text(`Unique Sessions: ${uniqueSessions}`, 105, 80, { align: 'center' });
  
  doc.addPage();
  
  // Table
  const tableData = locations.map(loc => [
    new Date(loc.timestamp).toLocaleString(),
    `${loc.latitude.toFixed(6)}, ${loc.longitude.toFixed(6)}`,
    `${loc.accuracy.toFixed(0)}m`,
    loc.browserName,
    loc.osName,
  ]);
  
  autoTable(doc, {
    head: [['Timestamp', 'Coordinates', 'Accuracy', 'Browser', 'OS']],
    body: tableData,
    startY: 20,
    styles: { fontSize: 8 },
    headStyles: { fillColor: [30, 64, 175] },
  });
  
  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.text(
      `Page ${i} of ${pageCount}`,
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
    doc.text(
      'Generated by UnQTraker',
      doc.internal.pageSize.getWidth() / 2,
      doc.internal.pageSize.getHeight() - 5,
      { align: 'center' }
    );
  }
  
  doc.save(`unqtraker-report-${new Date().toISOString().split('T')[0]}.pdf`);
};
